version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/code
  mysql:
    environment:
      - MYSQL_DATABASE="node"
      - MYSQL_ROOT_PASSWORD="1234"
    image: "mysql:5.7"
